matrix:
  include: 
    - os: linux
      jdk: openjdk8
    - os: osx
      osx_image: xcode9.3

script:
  - npm install
  - npm pack --silent
  # Check that we are able to install our package.
  - npm install -g *.tgz
